### ISSUE TITLE
org.joda.time.LocalDateTime not supported by Json

### ISSUE THREAD

**Issue by bissaias** [vert-x3/vertx-mysql-postgresql-service#4]
According to Mauricio Linhares the async driver always returns JodaTime when dealing with date types and not the `java.util.Date` class. However, so far this is not supported by the `io.vertx.core.json.impl.Json.checkAndCopy` method which throws the following exception:
```
java.lang.IllegalStateException: Illegal type in JsonObject: class org.joda.time.LocalDateTime
	at io.vertx.core.json.impl.Json.checkAndCopy(Json.java:94)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:215)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowToJsonArray$1.apply(AsyncSqlConnectionImpl.scala:150)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowToJsonArray$1.apply(AsyncSqlConnectionImpl.scala:148)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.github.mauricio.async.db.general.ArrayRowData.foreach(ArrayRowData.scala:22)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at com.github.mauricio.async.db.general.ArrayRowData.map(ArrayRowData.scala:22)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl.io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowToJsonArray(AsyncSqlConnectionImpl.scala:148)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowDataSeqToJsonArray$1.apply(AsyncSqlConnectionImpl.scala:141)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowDataSeqToJsonArray$1.apply(AsyncSqlConnectionImpl.scala:139)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.github.mauricio.async.db.general.MutableResultSet.foreach(MutableResultSet.scala:27)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at com.github.mauricio.async.db.general.MutableResultSet.map(MutableResultSet.scala:27)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl.io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$rowDataSeqToJsonArray(AsyncSqlConnectionImpl.scala:139)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$queryResultToResultSet$1.apply(AsyncSqlConnectionImpl.scala:129)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$queryResultToResultSet$1.apply(AsyncSqlConnectionImpl.scala:126)
	at scala.Option.map(Option.scala:145)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl.io$vertx$ext$asyncsql$impl$AsyncSqlConnectionImpl$$queryResultToResultSet(AsyncSqlConnectionImpl.scala:126)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$query$2.apply(AsyncSqlConnectionImpl.scala:50)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$query$2.apply(AsyncSqlConnectionImpl.scala:50)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$done$1.apply(AsyncSqlConnectionImpl.scala:161)
	at io.vertx.ext.asyncsql.impl.AsyncSqlConnectionImpl$$anonfun$done$1.apply(AsyncSqlConnectionImpl.scala:160)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at io.vertx.ext.asyncsql.impl.pool.SimpleExecutionContext$$anon$1.execute(SimpleExecutionContext.scala:12)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at io.vertx.ext.asyncsql.impl.pool.SimpleExecutionContext$$anon$1.execute(SimpleExecutionContext.scala:12)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Promise$class.success(Promise.scala:89)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:153)
	at com.github.mauricio.async.db.mysql.MySQLConnection$$anonfun$succeedQueryPromise$1.apply(MySQLConnection.scala:205)
	at com.github.mauricio.async.db.mysql.MySQLConnection$$anonfun$succeedQueryPromise$1.apply(MySQLConnection.scala:205)
	at scala.Option.foreach(Option.scala:256)
	at com.github.mauricio.async.db.mysql.MySQLConnection.succeedQueryPromise(MySQLConnection.scala:204)
	at com.github.mauricio.async.db.mysql.MySQLConnection.onResultSet(MySQLConnection.scala:214)
	at com.github.mauricio.async.db.mysql.codec.MySQLConnectionHandler.handleEOF(MySQLConnectionHandler.scala:289)
	at com.github.mauricio.async.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.scala:104)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Narigo** [comment]
Sorry for getting back to you so late. Should be fixed when #8 is pulled in, I hope.

**Comment by bissaias** [comment]
I tested it and it seems OK, many thanks. One more question just to make sure I got this right: Date, Time and DateTime parameters when the `io.vertx.ext.sql.SqlConnection.updateWithParams()` method is used should be passed as ISO 8601 formatted strings, correct?

**Comment by Narigo** [comment]
I guess so. At least Date is tested with `YYYY-MM-DD` and Timestamp with
`YYYY-MM-DDTHH:mm:ss.SSS+HH:mm`
Am 22.02.2015 17:00 schrieb "Veniamin Isaias" <notifications@github.com>:

**Comment by Narigo** [comment]
Closing as #8 is merged. If there is still a problem, please reopen this issue. Thanks! :)
